name: driver_tracking_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.6
  flutter_map: ^7.0.2
  latlong2: 0.9.1
  flutter_riverpod: ^2.5.1
  geolocator: ^12.0.0
  go_router: ^14.2.1
  hive: ^2.2.3
  http: ^1.2.1
  onesignal_flutter: ^5.2.2
  permission_handler: ^11.3.1
  riverpod: ^2.5.1
  flutter_dotenv: ^5.1.0
  open_route_service: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: Arciform
      fonts:
        - asset: assets/fonts/arciform.otf
  uses-material-design: true
  
  assets:
    - .env

